# Generated by Django 2.1.5 on 2019-01-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190118_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
        migrations.AddField(
            model_name='item',
            name='date_title',
            field=models.CharField(max_length=100, null=True, verbose_name='date_title'),
        ),
        migrations.AddField(
            model_name='item',
            name='keyword_link',
            field=models.CharField(max_length=100, null=True, verbose_name='keyword_link'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_link',
            field=models.CharField(max_length=100, null=True, verbose_name='title_link'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
